
# connexion à SonarQube
sonar.host.url=http://localhost:9000
sonar.token=sqp_4add943c95135a18b4be859997471b6ea3fc7bf6
sonar.projectKey=frontend-projet

# ne prendre que ton code client (pas de tests ici)
sonar.sources=src

# exclure explicitement tout ce qui n'est pas du code applicatif
sonar.exclusions=**/node_modules/**


